"""RBAC declarativo: mapeo rol -> permisos.

Intervenir en producción en lugar de role_permissions para el MVP; a futuro la
tabla `role_permissions` de la BD puede tomar el control sin romper la API.
"""
from __future__ import annotations

ROLE_SUPER_ADMIN = "SUPER_ADMIN"
ROLE_OWNER = "OWNER"
ROLE_ADMIN = "ADMIN"
ROLE_SUPERVISOR = "SUPERVISOR"
ROLE_RECEPTION = "RECEPTION"
ROLE_TECHNICIAN = "TECHNICIAN"
ROLE_MECHANIC = "MECHANIC"
ROLE_WAREHOUSE = "WAREHOUSE"
ROLE_CASHIER = "CASHIER"

ALL_PERMISSIONS: set[str] = {
    "tenants.view",
    "users.view",
    "users.create",
    "users.update",
    "users.delete",
    "settings.view",
    "settings.update",
    "dashboard.view",
    "clients.view",
    "clients.create",
    "clients.update",
    "clients.delete",
    "vehicles.view",
    "vehicles.create",
    "vehicles.update",
    "vehicles.delete",
    "appointments.view",
    "appointments.create",
    "appointments.update",
    "appointments.delete",
    "receptions.view",
    "receptions.create",
    "receptions.update",
    "diagnostics.view",
    "diagnostics.create",
    "diagnostics.update",
    "quotes.view",
    "quotes.create",
    "quotes.update",
    "quotes.send",
    "quotes.approve",
    "quotes.reject",
    "quotes.convert",
    "work_orders.view",
    "work_orders.create",
    "work_orders.update",
    "work_orders.change_status",
    "work_orders.approve",
    "work_orders.deliver",
    "services.view",
    "services.create",
    "services.update",
    "services.delete",
    "technicians.assign",
    "labor.create",
    "labor.update",
    "labor.delete",
    "parts.view",
    "parts.create",
    "parts.update",
    "inventory.view",
    "inventory.movements",
    "inventory.adjust",
    "payments.view",
    "payments.register",
    "warranties.view",
    "warranties.create",
    "warranties.update",
    "files.upload",
    "files.delete",
    "audit.view",
}

PERMISSIONS_BY_ROLE: dict[str, set[str]] = {
    ROLE_SUPER_ADMIN: set(ALL_PERMISSIONS),
    ROLE_OWNER: set(ALL_PERMISSIONS),
    ROLE_ADMIN: set(ALL_PERMISSIONS),
    ROLE_SUPERVISOR: {
        "dashboard.view",
        "clients.view",
        "vehicles.view",
        "appointments.view",
        "receptions.view",
        "diagnostics.view",
        "diagnostics.create",
        "diagnostics.update",
        "quotes.view",
        "quotes.create",
        "quotes.update",
        "quotes.send",
        "quotes.approve",
        "work_orders.view",
        "work_orders.create",
        "work_orders.update",
        "work_orders.change_status",
        "work_orders.approve",
        "work_orders.deliver",
        "services.view",
        "technicians.assign",
        "labor.create",
        "labor.update",
        "labor.delete",
        "parts.view",
        "inventory.view",
        "warranties.view",
        "warranties.create",
        "audit.view",
    },
    ROLE_RECEPTION: {
        "dashboard.view",
        "clients.view",
        "clients.create",
        "clients.update",
        "vehicles.view",
        "vehicles.create",
        "vehicles.update",
        "appointments.view",
        "appointments.create",
        "appointments.update",
        "receptions.view",
        "receptions.create",
        "receptions.update",
        "work_orders.view",
        "work_orders.create",
        "quotes.view",
        "quotes.create",
        "files.upload",
    },
    ROLE_TECHNICIAN: {
        "dashboard.view",
        "vehicles.view",
        "work_orders.view",
        "diagnostics.view",
        "diagnostics.create",
        "diagnostics.update",
        "labor.create",
        "labor.update",
        "parts.view",
        "files.upload",
    },
    ROLE_MECHANIC: {
        "dashboard.view",
        "vehicles.view",
        "work_orders.view",
        "diagnostics.view",
        "diagnostics.create",
        "diagnostics.update",
        "labor.create",
        "labor.update",
        "parts.view",
        "files.upload",
    },
    ROLE_WAREHOUSE: {
        "dashboard.view",
        "parts.view",
        "parts.create",
        "parts.update",
        "inventory.view",
        "inventory.movements",
        "inventory.adjust",
        "audit.view",
    },
    ROLE_CASHIER: {
        "dashboard.view",
        "clients.view",
        "vehicles.view",
        "work_orders.view",
        "payments.view",
        "payments.register",
        "quotes.view",
    },
}


def role_has_permission(role: str, permission: str) -> bool:
    perms = PERMISSIONS_BY_ROLE.get(role) or set()
    return permission in perms or role == ROLE_SUPER_ADMIN